---
page-layout: article
date: "2023-12-22"
title: "Métricas de Performance de Modelos de Regressão"
author: "Elpídio Filho & ChatGPT"
toc: true
toc-title: "Table of Content"
categories:
  - Machine Leaning
  - Métricas de performance de modelos
---


### Métricas de Performance de Modelos de Regressão

Os modelos de regressão são amplamente utilizados em machine learning para prever valores numéricos contínuos. Para avaliar a performance desses modelos, utilizamos várias métricas quantitativas. As mais comuns são R-quadrado (R²), Root Mean Squared Error (RMSE) e Mean Absolute Error (MAE). Cada uma dessas métricas tem suas próprias características, vantagens e desvantagens.

#### R-quadrado (R²)

O R-quadrado é uma métrica que indica a proporção da variância dos dados que é explicada pelo modelo. Ele varia entre 0 e 1, onde 1 indica que o modelo explica toda a variância dos dados.

**Cálculo:**

$$
 R^2 = 1 - \frac{\sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{\sum_{i=1}^{n} (y_i - \bar{y})^2} 
$$
-   ( y_i ) são os valores reais.
-   ( \hat{y}\_i ) são os valores preditos pelo modelo.
-   ( \bar{y} ) é a média dos valores reais.

**Vantagens:** - Fácil de interpretar. - Indica a proporção da variância explicada pelo modelo.

**Desvantagens:** - Pode ser enganoso em modelos com muitos preditores. - Não penaliza modelos complexos.

#### Root Mean Squared Error (RMSE)

O RMSE mede a média das diferenças ao quadrado entre os valores reais e os valores preditos. Ele dá uma ideia da magnitude do erro.

**Cálculo:**
$$
 RMSE = \sqrt{\frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2} \
$$
**Vantagens:** - Penaliza erros grandes, pois os erros são elevados ao quadrado. - Útil para comparar a performance de diferentes modelos.

**Desvantagens:** - Pode ser influenciado por outliers, já que eleva os erros ao quadrado.

#### Mean Absolute Error (MAE)

O MAE calcula a média das diferenças absolutas entre os valores reais e os valores preditos. Ele fornece uma visão clara da magnitude do erro sem amplificar erros grandes.

**Cálculo:**

$$
MAE = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}_i|
$$


**Vantagens:** - Fácil de interpretar. - Menos sensível a outliers comparado ao RMSE.

**Desvantagens:** - Não penaliza erros grandes de forma mais severa.

### Considerações Finais

Ao avaliar modelos de regressão, é importante considerar múltiplas métricas para ter uma visão completa da performance. O R² é útil para entender quanta variação do alvo é explicada pelo modelo, mas pode ser otimista em modelos complexos. O RMSE fornece uma ideia da magnitude dos erros, penalizando erros grandes, enquanto o MAE oferece uma interpretação direta do erro médio.

Escolher a métrica certa depende do contexto e dos objetivos do modelo. Em alguns casos, a combinação de várias métricas pode oferecer uma análise mais robusta e abrangente da performance do modelo.
